### ISSUE TITLE
Edges are still overlapped on bidirectional connections

### ISSUE THREAD

**Issue by mgimenez** [tisoap/react-flow-smart-edge#10]
If you have something like:

`{
    id: 'e4-5',
    source: '4',
    target: '5',
    arrowHeadType: 'arrowclosed',
    label: 'label e-4-5',
  },
  {
    id: 'e5-4',
    source: '5',
    target: '4',
    type: 'smoothstep',
    label: 'label e-5-4'
  },`

they will look overlapped.

**Comment by tisoap** [comment]
@mgimenez Do you mean Edges overlapping each other? This problem is outside the scope of this component (avoiding intersections with Nodes, not Edges). You'll need to make your own custom Edge for this scenario, or try different/more connection points to avoid intersections.

Depending on the amount of Nodes and Edges, making a custom Edge that never intersects with other Edges can be impossible. It's the same scenario as the [Three utilities problem](https://en.wikipedia.org/wiki/Three_utilities_problem).

**Comment by mgimenez** [comment]
Hey @tisoap, thanks for responding, I mean overlap nop intersect. Anyways I already solved. Thanks
