### ISSUE TITLE
SmartStepEdge with Button

### ISSUE THREAD

**Issue by abhishekopsteq** [tisoap/react-flow-smart-edge#21]
![image](https://user-images.githubusercontent.com/95271692/165094835-86639267-1055-43ae-b053-7dff5eb89671.png)
Hey @tisoap,
I am going to implement SmartStetpEdge with( importing  {SmartStepEdge}  from '@tisoap/react-flow-smart-edge') Button but I didn't see any methods like getBezierPath, getSmoothStepPath
Could you please help me on that

**Comment by tisoap** [comment]
Hey @abhishekopsteq ! Could you please expand on that? There's no exported methods with those names in this library

**Comment by abhishekopsteq** [comment]
![image](https://user-images.githubusercontent.com/95271692/165233619-8a1d20f0-42c4-40a3-a23e-22333abef8e5.png)
Hello @tisoap,
I'm attempting to add a button with SmartStepEdge similar to the image above. I drew the button in that image with blue pens.

**Comment by tisoap** [comment]
I understand now, unfortunately the edges from this package currently don't provide any way to create custom labels with buttons or other HTML elements. [Another user reported this as an enhancement](https://github.com/tisoap/react-flow-smart-edge/issues/23), so I'll close this issue here as a duplicate.
